ALTER TABLE coursemapping MODIFY COLUMN FacultyUID VARCHAR(5) NULL;
ALTER TABLE coursemapping MODIFY COLUMN Mergecode VARCHAR(7) NULL;
ALTER TABLE coursemapping MODIFY COLUMN Reserveslot VARCHAR(50) NULL;
